# Generated by Django 6.0.6 on 2026-07-01 09:15

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('plumber', 'Mega Plumber Meet'), ('dealer', 'Dealer Meet')], max_length=50)),
                ('main_image', models.ImageField(help_text='Primary cover image for the event.', upload_to='events/main/')),
                ('description', models.TextField(blank=True, help_text='Short teaser description.', null=True)),
                ('rich_description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Rich detailed description with uploads.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('warehouse_exists', models.BooleanField(default=False)),
                ('experience', models.TextField(help_text='Current brands, suppliers, or general industry experience.')),
                ('message', models.TextField(blank=True, help_text='Additional partner message.', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('upvc', 'uPVC Pipes'), ('pvc', 'PVC Pipes'), ('cpvc', 'CPVC Pipes'), ('swr', 'SWR Pipes'), ('fittings', 'Ball Valve / Fittings')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the product and its applications.')),
                ('image', models.ImageField(help_text='Product showcase image.', upload_to='products/')),
                ('technical_specifications', models.TextField(blank=True, help_text='Sizing tables or specific technical details.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery photos linked to this event.', upload_to='events/gallery/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.event')),
            ],
        ),
    ]
