# Generated by Django 6.0.6 on 2026-07-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='FILTEC Polyplast Catalog', max_length=200)),
                ('embed_url', models.URLField(help_text='OneDrive or Google Drive embed URL. (e.g., https://onedrive.live.com/embed?resid=... or Google Drive preview URL).', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to True to make this the active catalog on the website. Only one should be active at a time.')),
            ],
        ),
    ]
